using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

namespace M4_major_project
{
    public partial class RegisterOTP : System.Web.UI.Page
    {
        protected void Page_Load(object sender, EventArgs e)
        {

        }
        protected void confirmBtn_Click(object sender, EventArgs e)
        {
            string temp = CurrentRegistration.getOtpString();
            string temp1 = otpTextBox.Text;
            if (CurrentRegistration.getOtpString().Equals(otpTextBox.Text))
            {
                Email.sendEmail(CurrentRegistration.getEmail(),"Welcome to The Cottage BnB",htmlWelcome());
                FullDataSet fullDs = new FullDataSet();
                FullDataSetTableAdapters.CustomerTableAdapter taCustomer = new FullDataSetTableAdapters.CustomerTableAdapter();
                taCustomer.Fill(fullDs.Customer);
                taCustomer.Insert(CurrentRegistration.getEmail(), CurrentRegistration.getName(), CurrentRegistration.getSurname(), CurrentRegistration.getIdNumber(), CurrentRegistration.getCellNumber(), CurrentRegistration.getPassword(), CurrentRegistration.getStreetName(), CurrentRegistration.getSuburb(), CurrentRegistration.getCity(), CurrentRegistration.getPostalCode());
                taCustomer.Update(fullDs.Customer);
                taCustomer.Fill(fullDs.Customer);
                CurrentUser.setEmailID(CurrentRegistration.getEmail());
                closeBtn.UseSubmitBehavior = false;
                modalBody.InnerHtml = "<p>You have successfully registered, You can now make bookings.<br/>We are redirecting You to our home page</p>";
                ScriptManager.RegisterStartupScript(this, this.GetType(), "Pop", "showModal();", true);
                confirmBtn.Enabled = false;
                Login.check = 1;
            }
           else
           {
                closeBtn.UseSubmitBehavior = true;
                modalBody.InnerHtml = "<p>OTP is incorrect please try again</p>";
                ScriptManager.RegisterStartupScript(this, this.GetType(), "Pop", "showModal();", true);
            }
        }
        protected void closeBtn_Click(object sender, EventArgs e)
        {
            Response.Redirect("/Default");
        }
        private string htmlWelcome()
        {
            string body = @"<html>
                           <body>";
            body += "<h1>Welcome to The Cottage BnB, " + CurrentRegistration.getName() + "!</h1><p><strong>This email includes your account details, so please keep it safe.</strong></p><p>We’re thrilled to see you here!</p>";
            body += "<p>We’re confident that The Cottage BnB will give you an enjoyable and unforgettable experience everytime you visit.</p>";
            body += "<p>Take care!</p>";
            body += "<p>This is an autogenerated email, for enquiries<br>call: +27 64 090 3388<br>Or email: sonya@TheCottageBnB.co.za</p>";
            body += " </body></html>";
            return body;
        }
    }
}